import type {
  ApiKeyStatus,
  AspectRatio,
  AssetKind,
  CameraMotion,
  CaptionAnimation,
  CaptionMode,
  CaptionPosition,
  CaptionStyle,
  ExportFormat,
  ExportResolution,
  FrameRate,
  JobStatus,
  JobType,
  KeyStrategy,
  ProjectStatus,
  SceneStatus,
  TemplateKind,
  TransitionType,
  UserRole,
} from './enums';

export interface User {
  id: string;
  email: string;
  name: string | null;
  avatarUrl: string | null;
  role: UserRole;
  createdAt: string;
}

export interface Project {
  id: string;
  userId: string;
  name: string;
  videoTitle: string | null;
  aspectRatio: AspectRatio;
  /** Target duration in seconds; null means "match the voiceover exactly". */
  targetDurationSec: number | null;
  language: string;
  status: ProjectStatus;
  progress: number;
  settings: ProjectSettings;
  qualityReport: QualityReport | null;
  errorMessage: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ProjectSettings {
  caption: CaptionSettings;
  transition: TransitionSettings;
  export: ExportSettings;
  broll: BrollSettings;
  characterLock: boolean;
  styleLock: boolean;
  /** Motion clips are generated by the image-to-video model when true. */
  motionEnabled: boolean;
}

export interface CaptionSettings {
  enabled: boolean;
  style: CaptionStyle;
  mode: CaptionMode;
  fontFamily: string;
  fontSize: number;
  primaryColor: string;
  highlightColor: string;
  outlineColor: string;
  shadowColor: string;
  outlineWidth: number;
  shadowDepth: number;
  position: CaptionPosition;
  marginVertical: number;
  uppercase: boolean;
  animation: CaptionAnimation;
  emoji: boolean;
  /** Words emphasised with the highlight colour, lower-cased. */
  keywords: string[];
  maxWordsPerCue: number;
}

export interface TransitionSettings {
  enabled: boolean;
  /** Empty means "let the transition engine choose per cut". */
  types: TransitionType[];
  /** 0 = hard cuts everywhere, 1 = maximum stylisation. */
  intensity: number;
  durationSec: number;
}

export interface ExportSettings {
  format: ExportFormat;
  resolution: ExportResolution;
  fps: FrameRate;
  videoBitrateKbps: number | null;
  audioBitrateKbps: number;
}

export interface BrollSettings {
  enabled: boolean;
  /** Maximum share of scenes that may be replaced with B-roll (0..1). */
  maxRatio: number;
  categories: string[];
}

export interface Asset {
  id: string;
  projectId: string | null;
  userId: string;
  kind: AssetKind;
  storageKey: string;
  filename: string;
  mimeType: string;
  bytes: number;
  durationSec: number | null;
  width: number | null;
  height: number | null;
  metadata: Record<string, unknown>;
  createdAt: string;
}

export interface TranscriptWord {
  text: string;
  start: number;
  end: number;
  confidence?: number;
}

export interface TranscriptSegment {
  id: string;
  index: number;
  text: string;
  start: number;
  end: number;
  speaker: string | null;
  words: TranscriptWord[];
}

export interface Transcript {
  id: string;
  projectId: string;
  assetId: string;
  language: string;
  text: string;
  segments: TranscriptSegment[];
  wordCount: number;
  durationSec: number;
  confidence: number;
  /** Set once the user clicks "Proceed To Video Generation". */
  approvedAt: string | null;
  version: number;
  createdAt: string;
  updatedAt: string;
}

export interface StyleDna {
  id: string;
  projectId: string;
  name: string;
  summary: string;
  colorPalette: string[];
  colorGrading: string;
  lighting: string;
  composition: string;
  cameraLens: string;
  cameraStyle: string;
  mood: string;
  realismLevel: string;
  artisticStyle: string;
  textureDetail: string;
  negativePrompt: string;
  /** Ready-to-append prompt fragment describing the whole look. */
  promptSuffix: string;
  sourceAssetIds: string[];
  locked: boolean;
  createdAt: string;
}

export interface CompetitorInsight {
  id: string;
  projectId: string;
  assetId: string | null;
  sourceUrl: string | null;
  editingPace: string;
  avgSceneDurationSec: number;
  storyStructure: string;
  captionStyle: string;
  transitionStyle: string;
  cameraMovement: string;
  hookStructure: string;
  visualRhythm: string;
  sceneDurationPattern: number[];
  recommendations: string[];
  createdAt: string;
}

export interface CharacterProfile {
  id: string;
  projectId: string;
  name: string;
  role: string;
  age: string;
  gender: string;
  skinTone: string;
  hair: string;
  face: string;
  bodyShape: string;
  clothing: string;
  accessories: string;
  voiceTone: string;
  /** Canonical description injected into every prompt featuring this person. */
  canonicalPrompt: string;
  referenceAssetId: string | null;
  locked: boolean;
  createdAt: string;
}

export interface Scene {
  id: string;
  projectId: string;
  index: number;
  startSec: number;
  endSec: number;
  narration: string;
  visualPrompt: string;
  negativePrompt: string | null;
  emotion: string;
  location: string;
  characterIds: string[];
  cameraMotion: CameraMotion;
  motionPrompt: string | null;
  transitionIn: TransitionType | null;
  isBroll: boolean;
  brollSubject: string | null;
  status: SceneStatus;
  imageAssetId: string | null;
  clipAssetId: string | null;
  /** Word-level cues carved out of the transcript for this scene. */
  words: TranscriptWord[];
  attempts: number;
  errorMessage: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Job {
  id: string;
  projectId: string;
  userId: string;
  type: JobType;
  status: JobStatus;
  progress: number;
  total: number;
  completed: number;
  failed: number;
  priority: number;
  attempts: number;
  message: string | null;
  errorMessage: string | null;
  payload: Record<string, unknown>;
  startedAt: string | null;
  finishedAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface RenderRecord {
  id: string;
  projectId: string;
  jobId: string | null;
  format: ExportFormat;
  resolution: ExportResolution;
  fps: FrameRate;
  status: JobStatus;
  assetId: string | null;
  downloadUrl: string | null;
  bytes: number | null;
  durationSec: number | null;
  qualityReport: QualityReport | null;
  createdAt: string;
  finishedAt: string | null;
}

export interface QualityMetric {
  key: string;
  label: string;
  score: number;
  weight: number;
  notes: string;
}

export interface QualityReport {
  overall: number;
  grade: 'A' | 'B' | 'C' | 'D' | 'F';
  metrics: QualityMetric[];
  warnings: string[];
  generatedAt: string;
}

export interface ApiKeyRecord {
  id: string;
  userId: string;
  name: string;
  maskedKey: string;
  enabled: boolean;
  priority: number;
  status: ApiKeyStatus;
  lastTestedAt: string | null;
  lastUsedAt: string | null;
  responseTimeMs: number | null;
  availableModels: string[];
  requestCount: number;
  failureCount: number;
  /** Set while the key is cooling down after a 429 / quota error. */
  cooldownUntil: string | null;
  statusMessage: string | null;
  createdAt: string;
}

export interface ApiKeyTestResult {
  keyId: string;
  status: ApiKeyStatus;
  ok: boolean;
  message: string;
  responseTimeMs: number;
  availableModels: string[];
  testedAt: string;
}

export interface Template {
  id: string;
  userId: string;
  kind: TemplateKind;
  name: string;
  description: string | null;
  payload: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
}

export interface KeyPoolSettings {
  strategy: KeyStrategy;
  maxConcurrentPerKey: number;
  cooldownSeconds: number;
  maxRetries: number;
}

export interface AdminStats {
  totalUsers: number;
  activeUsers: number;
  totalProjects: number;
  completedProjects: number;
  failedJobs: number;
  storageBytes: number;
  apiCalls: number;
  apiTokens: number;
  estimatedCostUsd: number;
  generation: {
    images: number;
    clips: number;
    renders: number;
    transcriptionMinutes: number;
  };
  revenue: {
    mrrUsd: number;
    payingUsers: number;
    arpuUsd: number;
  };
}

export interface ProgressEvent {
  projectId: string;
  jobId: string | null;
  type: JobType | 'project';
  status: JobStatus | ProjectStatus;
  progress: number;
  message: string;
  at: string;
}
